### ISSUE TITLE
Trying to send generic data 

### ISSUE THREAD

**Issue by mgiganto** [Portisch/RF-Bridge-EFM8BB1#101]
Hi @Portisch,

Thank you for tis great software! I just wish to have more rom so it can accommodate more functionality...

### Latest firmware used?
Used Keil 8051 v9.53 - Release

### Information
I have a sonoff rf bridge R2. Since there is not much free space for implementing protocols I was thinking in a script that translates by protocol, so we can implement for example all the rtl 433 protocols in a python script and execute it from node-red/home assistant.
I did sniff a B1 sonoff button and I am trying to replicate it using the A8 command, I know it is implemented already, but I am trying to send it using the generic way specifying all the parameters... 
The reason to use A8 is because it can accept hex data, while the B0 command uses nibbles format, and I don't know/see a way to convert from any hex data to nibbles.
So At the beginning I was using AA A8 LEN 

### Sniffed data
18:49:43 RSL: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 02E4 1F0E 28181819081818190819081909090819090909081908181818 55"}}
AA B0 21 03 08 0122 02E4 1F0E 28181819081818190819081909090819090909081908181818 55
AA B1 03 0122 02E4 1F0E 28181819081818190819081909090819090909081908181818 55

0:0122	290
1:02E4	740
2:1F0E	7950 -< 
			2 818181908181819081908190909081909090908190818181 8

Sync: 30 Data: 818181908181819081908190909081909090908190818181
Sync: 30 Data: 81 81 81 90 81 81 81 90 81 90 81 90 90 90 81 90 90 90 90 81 90 81 81 81
Sync		   0  0  0  1  0  0  0  1  0  1  0  1  1  1  0  1  1  1  1  0  1  0  0  0
000100010101110111101000
Data in HEX: 115DE8

SYNC_HIGH: bucket 2 - 1F0E 7950  
SYNC_LOW: bucket 
BIT_HIGH_TIME: bucket 0 - 0122 290
BIT_HIGH_DUTY: (100% / (740+290))*290= 28.1% -> 28 -> 0x1C
BIT_LOW_TIME:  bucket 1 - 02E4 740
BIT_LOW_DUTY:  (100% / (740 + 290))*740= 71.8% -> 72 -> 0x48
BIT_COUNT + SYNC_BIT_COUNT: 0x18 (24)
LEN: 1E (30: 7F 1F0E ???? 0122 1C 02E4 48 18 115DE8) 
I tried this format: 
'AA A8 DATA_LEN 7F SYNC_HIGH SYNC_LOW BIT_HIGH_TIME BIT_HIGH_DUTY BIT_LOW_TIME BIT_LOW_DUTY BIT_COUNT_+_SYNC_BIT_COUNT DATA_HEX 55'

'AA A8 1E 7F 1F0E SYNC_LOW 0122 1C 02E4 48 18 115DE8 55'
And tried all the buckets for SYNC_LOW but no luck.

So I went to the code and the protocols to see details of 7F protocol and I didn´t find anything
Then I dig more and I found some changes and the use of mode 80

'AA A8 DATA_LEN 80 SYNC_HIGH SYNC_LOW PULSE_TIME BIT_0_HIGH_FACTOR BIT_0_LOW_FACTOR BIT_1_HIGH_FACTOR BIT_1_LOW_FACTOR SYNC_BIT_COUNT BIT_COUNT DATA_HEX 55'
So I build this command: 
AAA8 20 80 0122 1F0E 0406 1C48481C 00 18 115DE8 55
LEN: 0x20 (32: size of "80 0122 1F0E 0406 1C48481C 00 18 115DE8")
And I tried a few values for PULSE_TIME, but I realize that doesn´t matter the value of the pulse time, something else is preventing my command to work properly, I think it´s related with DATA_LEN.
Anyway, could you please help me with the values for an A8 protocol 7F and protocol 80, so I can keep working with that Idea...

Is there any other way to send data without using the implemented protocol?

The current wiki help is not mentioning anything nor giving details or examples about this A8 7F, A8 80, only about B1 2 B0, but I can´t read/write data using B1/B0

My next step will be decoding and sending fake temperature signals to digoo station:
 22:03:14 RSL: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 05 0230 074E 0384 0190 0EEC 4818080818081808281828282828282828182818281828281818181818080818281818180838 55"}}
rfraw AA B0 32 05 08 0230 074E 0384 0190 0EEC 4818080818081808281828282828282828182818281828281818181818080818281818180838 55
16.9ºC 62.4ºF
This B0 is working

Best regards

**Comment by Portisch** [comment]
The generic transfer is not supported anymore!
You can define a new matching protocol and disable some other unused to save storage.
Otherwise you will need to create a script to confert hey-data to data nibbles for a 0xB0 command.
