### ISSUE TITLE
RFRaw Storage/Gateway

### ISSUE THREAD

**Issue by Meesen0743** [Portisch/RF-Bridge-EFM8BB1#113]
Sorry to create an "Issue" but I am very new to this, 
Firstly I do not have a problem as such but I am a'bit stuck trying to figure out what to do next.

This previous weekend I got around to upgrading my Sonoff RF Bridge with the Portisch firmware and because of that I have made a'lot of progress sniffing, converting and re-sending with 2 generic remotes i have (unusable prior to the firmware upgrade) 

Now that I have the re-sending sorted, I am trying to find a way to either store the raw code on the RF-Bridge or pass on the Raw data via mqtt to then have a sensor pickup the data.

My end goal is to have an automation run in home assistant when a specific button press is detected.  

Any help would be greatly appreciated!
Meesen0743

**Comment by Portisch** [comment]
https://github.com/arendst/Sonoff-Tasmota
https://github.com/arendst/Sonoff-Tasmota/wiki
https://groups.google.com/forum/#!forum/sonoffusers
