### ISSUE TITLE
Codes from wall-remote only discovered in raw-mode

### ISSUE THREAD

**Issue by 10mabo** [Portisch/RF-Bridge-EFM8BB1#117]
Hello, 

I have flashed a sonoff rf bridge V2 with tasmota and the portisch firmware. I have a portable remote control and a wall-remote. The portable remote works just fine, but with the wall-remote, the bridge receives codes only in raw mode (RfRaw 177). In normal operation mode (after powering on the bridge), nothing is received.

Picture of the wall-remote: https://i.ebayimg.com/images/g/o0YAAOSwIWVY9xfz/s-l500.jpg

I woud like to use the bridge mostly as an rf receiver that reacts on button presses of the rf remotes to control non-rf devices for example wifi plugs (with node-red).

As the bridge seems to discover the wall-remotes button presses only in raw mode - is it possible to configure the bridge to permanently stay in raw mode? Or what else could I do... is there a mode that discovers raw an "normal" codes and sends it over mqtt?

Best regards,
Marc

**Comment by Portisch** [comment]
Handle it like here: https://github.com/Portisch/RF-Bridge-EFM8BB1/issues/118
Add your own protocol for 0xA6 sniffing. This more repeatable than 0xB1 sniffing.
Then use mqtt to activate the sniffing on boot.
