### ISSUE TITLE
Sonoff iFan03 compatibility?

### ISSUE THREAD

**Issue by mgoeller** [Portisch/RF-Bridge-EFM8BB1#147]
Has anyone every tried to flash the Portisch firmware on the RF chip of the Sonoff iFan03?

Goal: I would like to make the iFan03 controllable with a different remote than the stock one.

Picture of the iFan03 pcb layout under the rf shield:
![61053693-097ee100-a3bc-11e9-8752-7ceabea6fe74](https://user-images.githubusercontent.com/40425388/72974783-e81d9980-3dcf-11ea-8787-e5b0334662c1.jpg)

Picture of test points on the bottom PCB side:
![IMG_2215](https://user-images.githubusercontent.com/40425388/72974948-3d59ab00-3dd0-11ea-8c69-c9979256e2c2.jpg)

I guess I would have to connect the C2CK, C2D and any GND pin to an Arduino Mega (waiting for my order currently...) and try to read / flash the firmware with efm8-arduino-programmer.

I'm open for any tips, suggestions and will update this post as soon as I received my Arduino Mega.

**Comment by hugofran** [comment]
Hi @mgoeller - did you ever have success with this project?

**Comment by mgoeller** [comment]
I unfortunately did not continue on this project.
