### ISSUE TITLE
Would this firmware work with this device?

### ISSUE THREAD

**Issue by henfri** [Portisch/RF-Bridge-EFM8BB1#16]
Hello,

thanks for looking into the Firmware. I cannot learn [this ](http://www.seav.it/sites/default/files/prodotti/schede_tecniche/Txx%204%20GB.pdf)device (see: [here](https://github.com/xoseperez/espurna/issues/861))
Would the new firmware help me?

Greetings,
Hendrik

**Comment by AlbertWeterings** [comment]
It looks like you have a PT2262 based remote,  it should have work with the original firmware as well as with this. Are you able to open the remote and confirm the type of chip inside?

**Comment by Jason2866** [comment]
@henfri  Try it with the portisch firmware. I couldnt learn "2262" Code with orig. firmware.
Now with portisch firmware it works perfect. Take a look at TASMOTA firmware. In newest release the flasher software is included. Flashing EFM Fimware is so easy now.
