### ISSUE TITLE
Controlling PowerGlide Blinds (hpr433a)

### ISSUE THREAD

**Issue by angustyler** [Portisch/RF-Bridge-EFM8BB1#21]
Please let me know if I have posted this in the wrong place and I will close/move it.

With Tasmota and Portisch installed on my Sonoff RF Bridge, I’ve been trying to automate my PowerGlide blinds but get no response from them. The remote for the blinds has an HPR433A RF unit.
By pressing the <open blind> button multiple times, I captured the following data from the web console:
AA	B1	05	1572	0654	02D1	015E	4104		01233223322332323232233232323232323230	55
AA	B1	05	152C	0654	02D3	0172	40F0		01233223322332323232233232323232323230	55
AA	B1	05	1536	0654	02CC	016C	41FE		0123322332233232323223323232323232323230	55
AA	B1	05	1522	065E	027B	0181	3E20		0123322332233232323223323232323232323230	55
AA	B1	05	1536	064A	0289	0186	3E02		0123322332233232323223323232323232323220	55
AA	B1	05	152C	0654	02D7	0181	415E		0123322332233232323223323232323232323230	55
AA	B1	05	152C	0654	0280	017F	3EDE		0123322332233232323223323232323232323220	55
AA	B1	05	152C	0654	02D8	0195	458C		0123322332233232323223323232323232323230	55
AA	B1	05	152C	0654	02A1	0184	3D94		0123322332233232323223323232323232323220	55
AA	B1	05	152C	064A	02D8	018E	3FF6		0123322332233232323223323232323232323230	55
AA	B1	05	152C	0654	029D	0186	3D58		0123322332233232323223323232323232323220	55
AA	B1	05	1536	064A	02DA	0192	3FEC		0123322332233232323223323232323232323230	55
AA	B1	06	152C	064A	02D9	017B	010E	3BA0	0123322332233232323223323232323232323220	55
AA	B1	05	152C	065E	02DF	014F	3C7C		0123322332233232323223323232323232323220	55
AA	B1	05	152C	065E	028B	0172	3E20		0123322332233232323223323232323232323220	55
AA	B1	05	152C	0654	02DB	0156	3BA0		0123322332233232323223323232323232323220	55
AA	B1	05	152C	065E	02DA	0163	3A4C		0123322332233232323223323232323232323220	55
AA	B1	05	152C	0654	02DB	0173	3DF8		012332233223323232322332323232323232322330	55
AA	B1	05	1522	065E	02D9	01A5	37CC		01233223322332323232233232323232323232233230	55
AA	B1	05	1522	065E	02E2	0156	3AD8		012332233223323232322332323232323232322330	55
AA	B1	05	1522	0654	028F	0177	368C		01233223322332323232233232323232323232233230	55
AA	B1	05	1518	065E	028F	0174	3678		01233223322332323232233232323232323232233230	55
AA	B1	05	1522	0654	02DF	0174	3BFA		01233223322332323232233232323232323232233220	55
AA	B1	06	1522	065E	02DD	0174	00F0	36A0	01233223322332323232233232323232323232233220	55
AA	B1	06	1522	065E	02E0	0171	00F0	36D2	01233223322332323232233232323232323232233220	55

These lines appeared on the console in the following format:
19:20:16 MQT: tele/sonoff_6.0.0a/RESULT = {"RfRaw":{"Data":"AA B1 05 152C 0654 02DB 0156 3BA0 0123322332233232323223323232323232323220 55"}}

Ignoring the rows with 6 buckets of timing data, I tried:
1.	Field 1: User AA to mark UART Sync Init
2.	Field 2: Replaced the B1 with B0 transmit bucketed RF data
3.	Field 3: Put 28 (i.e. 40 decimal) – guessing this is the number of digits in the RF data to be transmitted
4.	Field 4: Used “05” as this is the number of timing buckets
5.	Field 5: Used “01” as assume repeating it once should be enough (noting original remote only transmits once)
6.	Field 6-10: The average value for each of the five columns of timing data
7.	Field 11: Took the most common value set for the RF data to be sent
8.	Field 12: used 55 to mark UART End Sync

AA	B0	28	05	01	152C	0656	02C1	0177	3DDD 0123322332233232323223323232323232323220	55

Hence, I executed the following on the console:
	rfraw 0xAAB0280501152C065602C101773DDD012332233223323232322332323232323232322055
Which flashed the red transmit LED and returned the result:
	10:10:13 MQT: stat/sonoff_6.0.0a/RESULT = {"RfRaw":"ON"}
	10:10:03 MQT: tele/sonoff_6.0.0a/RESULT = {"RfRaw":{"Data":"AAA055"}}
and no response from the blinds. I tried many times from very close to a few meters away with this same result every time.

Any help hugely appreciated and I have run out of ideas!

**Comment by Portisch** [comment]
No answer - closed...
