### ISSUE TITLE
HT6P20B Is supported?

### ISSUE THREAD

**Issue by xalexslx** [Portisch/RF-Bridge-EFM8BB1#22]
Hi,

I have the RF-Bridge with tasmota 6.0.0c and this firmware on the efm8bb1 chip. I'm trying to make my RF Bridge work with a motion sensor and a RF controller which controls my garage door. Both uses the HT6P20B protocol.

According to this link (https://acturcato.wordpress.com/2014/01/04/decoder-for-ht6p20b-encoder-on-arduino-board-english/) it is possible to learn this protocol using a normal receiver on arduino. I believe if this is possible, can we make it work on RF Bridge as well?

On the same pages it describes how the protocol is:

- The HT6P20B generates a code 28-bit, 22-bit for ADDRESS, 2-bit for DATA and 4-for “ANTI-CODE” (verification code).
- The ADDRES is fixed for a given Encoder (each HT6P20 has a different address).
- The DATA changes according to the pressed button.
- ANTI-CODE is always the same: “0101”.
- For HT6P20D model there are 20-bit for ADDRESS and 4-bit for DATA.
- For HT6P20F model there are 19-bit for ADDRESS and 5-bit for DATA.

I tried to use the sniffing mode and all I got from my motion sensor is:
```
05:21:18 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 04 01FD 03DF 0082 2CB0 0100101010101011010100101001010100110100110101001011001100 55"}}
05:21:27 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01EC 03E3 2CA6 0100101010101011010100101101010100110100110101001011001100 55"}}
05:21:28 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 05 01FA 03DB 006E 0140 2CB0 010100101010101011010100101101010100110100110101001011001100 55"}}
05:21:44 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 04 03D8 01FF 041A 2CB0 1011010101010100101011010010101011001011001010110100110010 55"}}
05:21:45 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 07 01FE 03D9 1621 007F 019A 00FA 2CB0 0100101010101011010100101101010100110100110101001011001100 55"}}
05:21:46 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01F9 03DF 2CBA 0100101010101011010100101101010100110100110101001011001100 55"}}
05:21:50 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 04 03E3 01F1 006E 2C42 1011010101010101001011010010101011001011001010110100110010 55"}}
05:21:51 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 04 01FD 03DA 006E 29D6 0100101010101011010100101001010100110100110101001011001100 55"}}
05:21:52 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 05 01F1 03E3 0140 00DC 2CA6 0100101010101011010100101101010100110100110101001011001100 55"}}
05:21:54 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01FC 03DE 2CBA 0100101010101011010100101101010100110100110101001011001100 55"}}
05:21:54 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 0219 03DD 2CBA 0100101010101011010100101101010100110100110101001011001100 55"}}
05:21:57 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 05 0226 03E6 09D8 0104 292C 0100101010101011010100101101010100110100110101001011001100 55"}}
05:22:00 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 06 03DD 0407 01FB 017C 00B4 2CA6 2022020202020200202022020020202022002022002020220200220020 55"}}
```

But sincerly I'm sure what to do with this data. HT6P20B is a very common protocol used for dumb alarm systems and garage doors here. As I already have some dumb alarm sensors and I don't want to mess with wires on my garage door, using my RF Controller and being able to clone it will be wonderful for my automation process.

**Comment by Portisch** [comment]
The main problem on this protocol is the inverse high/low of the bit 0 & 1.
The bit decoding implemented is triggering on a rising edge. So this can't be used for these HT6P20 devices.

You can retransmit the received buckets with the 0xB0 command. But I am a little bit confused because here is also the sync bucket marking in the bit data missing like here: #21

**Comment by xalexslx** [comment]
@Portisch 
These are the readings from my garage door HT6P20

```
17:49:23 MQT: stat/RF-Bridge1/RESULT = {"RfRaw":"ON"}
17:49:23 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AAA055"}}
17:49:39 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DA 03BC 2A80 0100110101010100110010101100101010110010110101001011001100 55"}}
17:49:46 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 04 01DB 03BD 078A 2AC6 0100110101010100110010101100101010110010110101001011001100 55"}}
17:49:49 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01D4 03C7 2AC6 0100110101010100110010101100101010110010110101001011001100 55"}}
17:49:57 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DE 03BC 2A80 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:06 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DB 03BC 2A80 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:06 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01E1 03BA 2A9E 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:08 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DC 03BC 2A80 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:08 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DC 03BB 2A94 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:08 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01D9 03BF 2A94 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:19 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01D9 03BC 2A8A 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:19 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DA 03BB 2A9E 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:36 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DB 03BC 2A80 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:36 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 03 01DC 03BF 2A9E 0100110101010100110010101100101010110010110101001011001100 55"}}
17:50:45 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 02 0172 1284 00 55"}}
17:50:46 MQT: tele/RF-Bridge1/RESULT = {"RfRaw":{"Data":"AA B1 02 0122 159A 55"}}
```

I tried to send the raw back using the #21 instructions but nothing happens.

```
rfraw 0xAAB0280501152C065602C101773DDD012332233223323232322332323232323232322055
rfraw 0xAAB10301DC03BF2A9E010011010101010011001010110010101011001011010100101100110055
rfraw 0xAAB01D0301DB03BC2A80010011010101010011001010110010101011001011010100101100110055
rfraw 0xAAB10301DB03BC2A80010011010101010011001010110010101011001011010100101100110055
```

I'm missing something from converting the B1->B0 data?

**Comment by Portisch** [comment]
This is the code of the garage? No rolling code? Not very save, isn't?

I checked the datasheet of  HT6P20D:
There is a sync of 23 clocks.
1 clock is bucket 0: 0x01DB
Sync should be 23 x 0x01DB = 0x2AAD what is almost matching the sniffed data 0x2A80.
Than there is one sync bit (clock), 20 address bits, 4 data bits and 4 anti-code bits.

On your example:

> "Data":"AA B1 03 01DB 03BC 2A80 0100110101010100110010101100101010110010110101001011001100 55"}}

It should be:
0 | 10 01 10 10 10 10 10 01 10 01 01 01 10 01 01 01 01 10 01 01 | 10 10 10 01 | 01 10 01 10 | 0
SYNC bit | address buckets | code buckets | anti buckets | SYNC bucket
The anti-code bits are matching.

So I think there is a bug in the firmware with the sync bucket number. It should look like this:
0 | 10 01 10 10 10 10 10 01 10 01 01 01 10 01 01 01 01 10 01 01 | 10 10 10 01 | 01 10 01 10 | 2

Please try this 0xB0 command:

> AA B0 xx 03 14 01DB 03BC 2A80 0 10 01 10 10 10 10 10 01 10 01 01 01 10 01 01 01 01 10 01 01 10 10 10 01 01 10 01 10 2 55

This will repeat 20 (0x14) times the code. Maybe less repeats are also working...
And here is the len (xx) replaced by 37 (0x25):

> AAB025031401DB03BC2A80010011010101010011001010110010101011001011010100101100110255

But I am also unsure about the low/high order. The 0xB0 command will transmit high/low.

**Comment by xalexslx** [comment]
@Portisch 

I tested with the following raw and it worked fine:

```
0xAAB025031401DB03BC2A80010011010101010011001010110010101011001011010100101100110255
```

Thanks, I wasn't able to convert myself.
