### ISSUE TITLE
Original Firmware

### ISSUE THREAD

**Issue by dellk** [Portisch/RF-Bridge-EFM8BB1#4]
Hi,
Can you please include the original firmware (as .hex) for the Sonoff EFM8BB1. I'd like to flash back. Since the new firmware only one remote is recognized by the RF Bridge.

**Comment by dellk** [comment]
Flashed OpenMQTTGateway instead of Espurna to test and at least one of the old remotes is being recognized again. 

Original EFM8BB1 firmware would be good nonetheless.

**Comment by AlbertWeterings** [comment]
Thank you for the great work on this project. Sorry I agree with @dellk and also want to be able to get back to the original firmware. At this point your firmware is not stable enough for use for sure I'm willing to test new versions later on.

**Comment by Portisch** [comment]
https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/8b3597517c67628677eae568aef3a520dcb0ae9f

**Comment by dellk** [comment]
Thank you. Will test and update.

**Comment by dellk** [comment]
Unfortunately it doesn't work. Flashing goes fine, but nothing gets received or sent.
