### ISSUE TITLE
which kind of signal is this and how to replicate it

### ISSUE THREAD

**Issue by tartesso26** [Portisch/RF-Bridge-EFM8BB1#40]
15:43:02 MQT: tele/TS_00000008/RESULT = {"RfRaw":{"Data":"AA B1 03 0134 023B 137E 110011001010110100101101001010110100110011010011001011001010101010101010101010101100101010101010101011001011001011001100101011001120 55"}}
15:43:02 MQT: tele/TS_00000008/RESULT = {"RfRaw":{"Data":"AA B1 04 13A6 025A 011E 137E 30 55"}}

when i push in the remote control, i get these 2 data, anybody has control some signal like this?

**Comment by Portisch** [comment]
https://github.com/Portisch/RF-Bridge-EFM8BB1/issues/31
