### ISSUE TITLE
Intertechno 32bit Code

### ISSUE THREAD

**Issue by boklubre** [Portisch/RF-Bridge-EFM8BB1#47]
Hi,
I use the RF-Bridge 433 to switch Intertechno plugs. With the standard firmware I only can use the old 12bit  code. It´s possible to use the newer 32bit Code with this firmware?
Cheers

Boris

**Comment by Portisch** [comment]
With the standard firmware you can use 24 bits. With this firmware you can use up to 896 bits. Take a look to the 0xA8 command.
