### ISSUE TITLE
Intertechno Code is not recognized

### ISSUE THREAD

**Issue by BigDi** [Portisch/RF-Bridge-EFM8BB1#50]
I have some IT sockets. The old ones are working. But I have some new devices
https://www.amazon.de/Trust-Funksteckdosen-Funk-Steckdosenschalter-Außenbereich-Fernbedienung/dp/B00HYEQTT6
that are not recognized also with B1 settings. Sometimes after pressing a couple times then I get one "hit". But it is not reproduceable. At the moment I use FHEM and a SIGNALduino and this combination showes the received code and I also can send to code to my socktes. Do you know SIGNALduino? It is only a small Arduino with a receiver/sender. The Arduino make a rudimentary decoding and real decoding works in FHEM.
I used a SonOff Bridge with Tasmota V6.3 and Version 0x02

**Comment by Portisch** [comment]
There is something unknown:  
https://github.com/athombv/homey/issues/52
Post a oscilloscope/logic analyser screen for more information.
If you own a Arduino try this firmware: https://github.com/sui77/SimpleRcScanner or https://github.com/sui77/rc-switch

**Comment by BigDi** [comment]
But SIGNALduino recognized this control.

**Comment by Portisch** [comment]
I do not have the hardware.
I do not have any sniffed data.
I do not have any debug data from RCswitch or other sniffing software.
I do not have any screen of the waveform.

What should I do?

**Comment by BigDi** [comment]
Is it not possible to port some parts of the code of the SIGNALduino? This one capture the code and identify it as IT Code.
https://github.com/RFD-FHEM/SIGNALDuino/blob/master/RF_Receiver/RF_Receiver.ino

**Comment by BigDi** [comment]
It seems that youe code clean broke some function...

**Comment by Portisch** [comment]
I know, use release 02. Use https://gist.github.com/Portisch/6dd5d6d20465521d76538a2907ba5e55 to convert to B0. Only bucket transfer can handle this protocol.
