### ISSUE TITLE
After update the red led blinkig fast continuously.

### ISSUE THREAD

**Issue by spider7611** [Portisch/RF-Bridge-EFM8BB1#56]
Updated the bridge EFM8BB1 chip without problem, but after restart the red led blinkig fast and never stopped. I reach the tasmota web page and do a reset but not solved the problem. the red led blinking and never stopped. Seems like always in learning mode. What can I do with this?

**Comment by Sepp0815** [comment]
Hey,
I have same effect here. No idea if it's normal or not as this is my first bridge that i use...

**Comment by Jason2866** [comment]
My Bridge has the same behaviour and does work well.
It shows that something is received (noise...)
Nothing do you have to fear about...

**Comment by Sepp0815** [comment]
@Portisch: Wie Du richtig vermutest, aus dem deutschsprachigen Raum, genauer gesagt aus dem süddeutschen Raum. Allerdings wird hier, wenn man's genau nimmt kein "richtiges" Deutsch gesprochen...;-)

Wollte eigentlich "nur mal schnell" ein paar alte Funksteckdosen, die ich hier noch rumliegen hatte, handyfähig machen und bin, weil das Anlernen der Codes nicht ablief, wie geplant; auf Deine Firmware aufmerksam geworden. Respekt für die Arbeit und das Projekt

**Comment by Portisch** [comment]
@Sepp0815 dangsche! Wer schauen das i's wida hin krieag. Schen gruas von Nähe Passau! ;)

**Comment by Portisch** [comment]
Should be fixed with [fixed RF sync detection on timing mode sniffing](https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/2a533bf5a664185a24d1db0f8abb39ccda508c9b)
