### ISSUE TITLE
Delight Kinetic Battery-free Wireless Doorbell

### ISSUE THREAD

**Issue by vampywiz17** [Portisch/RF-Bridge-EFM8BB1#57]
Hello there,

I flash Tasmota and this latest radio FW. my first plan to use this doorbell:

http://www.globiz.info/index.php?page=product&product_id=55340

But unfortunately RF bridge can not see any code. What do you think, it possible to see it in the future? I can not do any info the doorbell (what protocol use it, etc..) i hope somebody able to check it.

I use the latest release (Version 0x02). It is possible that is working with newer version firmware? if yes, which one i need to test it?

**Comment by Portisch** [comment]
[0xB1](https://github.com/Portisch/RF-Bridge-EFM8BB1/wiki/0xB1)?
Currently I have to stop development of this firmware.
The soic is running out of space.

I think about to split the firmware in "normal" use and "sniffing" use...

**Comment by vampywiz17** [comment]
I try this code: `rfraw aab155`

No success.

**Comment by Portisch** [comment]
than maybe the sync bucket is < 1300µs!?
You have an Arduino?

**Comment by vampywiz17** [comment]
No only a UART converter.

**Comment by vampywiz17** [comment]
If the RF bridge not blinking (not see any RF signal) if i push the doorbell button, that mean it no reason to try to flash a newer hex file my RF chip?

So it mean that the doorbell is a different freq?

Or, it only mean that is can not decode it and i have a chance that it will work with newer hex file?

**Comment by vampywiz17** [comment]
I try latest firmware (beta 3) but no success. Any possibility that i able to help you to find the problem? unfortunately no any arduino device or similar hardware...

**Comment by Portisch** [comment]
> unfortunately no any arduino device or similar hardware...
not without any additional hardware
