### ISSUE TITLE
Interactive Version of BitbuckedConverter

### ISSUE THREAD

**Issue by henfri** [Portisch/RF-Bridge-EFM8BB1#63]
Hello,

I have created an interactive version of Bitbuckedconverter:
https://github.com/henfri/bitbuckedconverter/commits/master/BitBucketConverter

I have documented each of the steps that I did. Please have a look at the history.
My changes do not only include this interactivity, but also some fixes.

Regards,
Hendrik

**Comment by Portisch** [comment]
https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/8ac3674f67f6f9fc1f19352df81e46a631dfac0f
Feel free to add pull requests...

**Comment by Portisch** [comment]
https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/8ac3674f67f6f9fc1f19352df81e46a631dfac0f
Feel free to add pull requests...

**Comment by henfri** [comment]
Done.
