### ISSUE TITLE
Can you add Dooya DC90 protocol to official release

### ISSUE THREAD

**Issue by deejaybeam** [Portisch/RF-Bridge-EFM8BB1#67]
Hi
There is a brunch with support for DC90 protocol. This one is used for my shutters too.
https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/1549715aa0e0bf4567d36c2b5018022ed60b9986
It would be nice if you could add this protocol to the official release.
best regards

**Comment by Portisch** [comment]
https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/c53fa5e1c47fc8ecda0a43c72c517b458666c6ce
