### ISSUE TITLE
Chinese door contact not recognized

### ISSUE THREAD

**Issue by mboberlin** [Portisch/RF-Bridge-EFM8BB1#68]
Hi,
i have some chinese door contacts which are recognized directly by the original firmware:

RESULT = {"RfReceived":{"Sync":11480,"Low":380,"High":1110,"Data":"143816","RfKey":"None"}}
RESULT = {"RfReceived":{"Sync":11480,"Low":380,"High":1120,"Data":"A42816","RfKey":"None"}}

in your firmware the key presses are not detected.
Greetings,
Michael

**Comment by Portisch** [comment]
Try sniffing again with the latest [master](https://github.com/Portisch/RF-Bridge-EFM8BB1/blob/master/Keil%208051%20v9.53%20-%20Release/RF-Bridge-EFM8BB1.hex)!

I close the issue because of a buggy EFM8 firmware - please do asniffing again and I will reopen the issue.
