### ISSUE TITLE
UNITEC switchable sockets

### ISSUE THREAD

**Issue by RobFromDE** [Portisch/RF-Bridge-EFM8BB1#70]
I am trying to control some switchable sockets from UNITEC, but they don't seem to react on my commands.

I installed the latest TASMOTA and EFM software. When I sniff the codes via "rfraw 177", I get the following output:

20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 0456 08B6 28181819081909081908190818181908181908181818181818 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1BA8 3818181908190908190819081818190818190818181818181A 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 044C 08C0 28181819081908181819081908190819081909090818181818 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B8A 3818181908190818181908190819081908190909081818181A 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 0456 08B6 28181819090818181908181819090819090819090818181818 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03CA 0BCC 1B94 3818181909081818190818181909081909081909081818181A 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08C0 28181819081819081818190909090818181819090818181818 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B8A 3818181908181908181819090909081818181909081818181A 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08B6 28181819081909081908190818181908181908181818181818 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03CA 0BD6 1B80 3818181908190908190819081818190818190818181818181A 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08AC 28181819081908181819081908190819081909090818181818 55"}}
20:47:03 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B8A 3818181908190818181908190819081908190909081818181A 55"}}
20:47:03 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 044C 08B6 28181819090818181908181819090819090819090818181818 55"}}
20:47:03 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03D4 0BC2 1B8A 3818181909081818190818181909081909081909081818181A 55"}}
20:47:03 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08B6 28181819081819081818190909090818181819090818181818 55"}}
20:47:03 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03CA 0BD6 1B8A 3818181908181908181819090909081818181909081818181A 55"}}
20:47:03 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08B6 28181819081909081908190818181908181908181818181818 55"}}
20:47:04 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03CA 0BCC 1B80 3818181908190908190819081818190818190818181818181A 55"}}
20:47:04 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 0442 08B6 28181819081908181819081908190819081909090818181818 55"}}
20:47:04 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03CA 0BCC 1B94 3818181908190818181908190819081908190909081818181A 55"}}
20:47:04 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 0456 08C0 28181819090818181908181819090819090819090818181818 55"}}
20:47:04 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03D4 0BC2 1B94 3818181909081818190818181909081909081909081818181A 55"}}
20:47:04 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 0456 08C0 28181819081819081818190909090818181819090818181818 55"}}
20:47:05 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03CA 0BCC 1B94 3818181908181908181819090909081818181909081818181A 55"}}
20:47:05 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 019A 044C 08C0 28181819081909081908190818181908181908181818181818 55"}}
20:47:05 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0212 03CA 0BD6 1B80 3818181908190908190819081818190818190818181818181A 55"}}
20:47:05 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 044C 08B6 28181819081908181819081908190819081909090818181818 55"}}
20:47:05 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B94 3818181908190818181908190819081908190909081818181A 55"}}
20:47:05 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 0456 08B6 28181819090818181908181819090819090819090818181818 55"}}
20:47:06 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03CA 0BCC 1B94 3818181909081818190818181909081909081909081818181A 55"}}
20:47:06 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 0442 08C0 28181819081819081818190909090818181819090818181818 55"}}
20:47:06 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B8A 3818181908181908181819090909081818181909081818181A 55"}}
20:47:06 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08B6 28181819081909081908190818181908181908181818181818 55"}}
20:47:06 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03CA 0BD6 1B8A 3818181908190908190819081818190818190818181818181A 55"}}
20:47:07 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 0442 08AC 28181819081908181819081908190819081909090818181818 55"}}
20:47:07 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B94 3818181908190818181908190819081908190909081818181A 55"}}

Storing this in a console.txt file and issuing the command:
python BitBucketConverter.py -f console.txt
I get the following output:

######
Filtered 0xB1 data: AAB1030186045608B62818181908190908190819081818190818190818181818181855

However I get no reaction on:

rfraw AAB1030186045608B62818181908190908190819081818190818190818181818181855

Am I doing something wrong?

**Comment by Portisch** [comment]
You have 4x4 codes. As I know some plugs need a minimum of 2 codes to switch on/off. I don't know if this will power on or off your plug because of missing information.
Sending a 0xB1 command will not work. It is 0xB0!

Here your example:
```
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 0456 08B6 28181819081909081908190818181908181908181818181818 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1BA8 3818181908190908190819081818190818190818181818181A 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 044C 08C0 28181819081908181819081908190819081909090818181818 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B8A 3818181908190818181908190819081908190909081818181A 55"}}
20:47:01 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0186 0456 08B6 28181819090818181908181819090819090819090818181818 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03CA 0BCC 1B94 3818181909081818190818181909081909081909081818181A 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0190 044C 08C0 28181819081819081818190909090818181819090818181818 55"}}
20:47:02 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 0208 03D4 0BCC 1B8A 3818181908181908181819090909081818181909081818181A 55"}}
```

And here the converted values:
```
Resulting 0xB0 data: AA B0 21 03 0A 0186 0456 08B6 82818181908190908190819081818190818190818181818181 55
Resulting 0xB0 data: AA B0 23 04 0A 0208 03D4 0BCC 1BA8 A3818181908190908190819081818190818190818181818181 55
Resulting 0xB0 data: AA B0 21 03 0A 0186 044C 08C0 82818181908190818181908190819081908190909081818181 55
Resulting 0xB0 data: AA B0 23 04 0A 0208 03D4 0BCC 1B8A A3818181908190818181908190819081908190909081818181 55
Resulting 0xB0 data: AA B0 21 03 0A 0186 0456 08B6 82818181909081818190818181909081909081909081818181 55
Resulting 0xB0 data: AA B0 23 04 0A 0208 03CA 0BCC 1B94 A3818181909081818190818181909081909081909081818181 55
Resulting 0xB0 data: AA B0 21 03 0A 0190 044C 08C0 82818181908181908181819090909081818181909081818181 55
Resulting 0xB0 data: AA B0 23 04 0A 0208 03D4 0BCC 1B8A A3818181908181908181819090909081818181909081818181 55
```

Untested!
