### ISSUE TITLE
I LumoS RF remote control learning

### ISSUE THREAD

**Issue by Fietspomp86** [Portisch/RF-Bridge-EFM8BB1#79]
Hey all,

Love this project.
Using an R2 Sonoff Bridge with Tasmota and the "generic_bucket" beta v3.
I have a nice dimmer panel from  [I Lumos](https://hartingtonheath.com/products/i-lumos-luxury-white-crystal-glass-touch-remote-dimmer-led-light-switches/), which came with an RF remote.
When trying to sniff the remote I do get some reaction in the console, but when i use the bitbucketconverter and send the commands, I get no response from my lights.

Here's the output from pressing "dim 1" and "dim 2" several times.
Attached pictures of the remote.

> 23:59:07 CMD: rfraw 177
23:59:07 MQT: stat/sonoff_bridge/RESULT = {"RfRaw":"ON"}
23:59:07 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AAA055"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 0154 00D2 0168 B09091A1A2 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 00E6 006E 0168 017C 380929 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00FA 019A 38181A 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 02 00FA 012C 180808 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0078 014A 00BE 0136 38181819292918 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 008C 012C 38181A0A 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0096 012C 015E 28181819090918 55"}}
23:59:09 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00D2 0136 38181819092918 55"}}
23:59:10 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0118 00BE 012C 281909 55"}}
23:59:10 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0096 0140 00E6 012C 38181819092918 55"}}
23:59:10 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 02 0104 012C 180808 55"}}
23:59:10 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 008C 010E 0172 A081909090 55"}}
23:59:10 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0096 014A 0136 28181819090918 55"}}
23:59:10 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0096 0136 00E6 012C 38181819092918 55"}}
23:59:11 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0096 012C 38181A0A 55"}}
23:59:11 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 014A 00C8 0136 38181819092918 55"}}
23:59:11 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 02 0104 012C 180808 55"}}
23:59:11 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00D2 0136 38181819092918 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 00B4 015E 0078 0154 B08092 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 00F0 0078 0168 0168 380929 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00D2 01EA 38181929281A2818181819281A2A2A2A2A2928181818190929 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0078 0140 00B4 0140 38181819292918 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00D2 0136 38181819092918 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0118 00AA 0136 281909 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00A0 0136 012C 28181819090918 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 006E 0154 00B4 0136 381818181929 55"}}
23:59:15 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0078 0154 00FA 0140 3818181A292918 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 014A 00DC 0168 B09091A1A1 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0096 014A 00FA 01EA 3818190908190818181819081A2A2A2A2A2A08181818190909 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00D2 0140 38181819092918 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 008C 012C 28080909 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 02 00E6 0140 180808 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00F0 008C 0136 2809090909 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00A0 0136 0136 28181819090918 55"}}
23:59:21 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 0140 00D2 012C 38181819092918 55"}}
23:59:24 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 0154 00D2 015E B09091A1A1 55"}}
23:59:24 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 006E 0172 00E6 0186 38181A 55"}}
23:59:24 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0078 0154 0186 281819 55"}}
23:59:24 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00FA 008C 012C 28080909 55"}}
23:59:24 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00AA 012C 0136 28181819090918 55"}}
23:59:24 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 014A 00E6 0136 38181819092918 55"}}
23:59:25 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0096 0136 012C 28181819090918 55"}}
23:59:25 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00F0 0082 0140 2809090909 55"}}
23:59:25 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0096 0140 0136 28181819090918 55"}}
23:59:25 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0078 015E 0104 0136 3818181A292918 55"}}
23:59:25 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00A0 0136 0136 28181819090918 55"}}
23:59:28 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00FA 008C 0168 2809090809 55"}}
23:59:28 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0096 0140 00DC 01D6 381819090819281818181908192A2A2A281908181908190909 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0096 012C 280909 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0078 0136 2809090809 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0118 00BE 0140 2819090819 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0096 0136 2809090819 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 012C 2819090819 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0096 0136 381A0A080A 55"}}
23:59:29 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 0140 2819090819 55"}}
23:59:33 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 00D2 0064 0168 0186 380929 55"}}
23:59:33 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 00E6 0064 0172 01CC 380929280908080A290908080908092929 55"}}
23:59:33 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 008C 012C 381A0A081A 55"}}
23:59:33 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00FA 0096 0140 2809090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 012C 2819090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0082 0140 381A0A080A 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00AA 0140 2819090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00F0 0082 0140 2809090809 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 010E 00B4 012C 2819090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0082 0140 38190A081A 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0096 0140 2809090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0096 012C 381A09081A 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00FA 008C 0140 2809090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0118 00B4 012C 2819090819 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0096 012C 381A0A081A 55"}}
23:59:34 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0078 0136 2809090809 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0078 00DC 0154 015E B091A0 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00F0 0082 01E0 2809090909 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 0140 00BE 012C 38192818 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0082 0140 381A0A081A 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 014A 2819090819 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00BE 0082 0136 381909080A 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0096 0136 2809090819 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 012C 2819090819 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0082 0140 2809090809 55"}}
23:59:39 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 0136 2819090819 55"}}
23:59:40 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0078 014A 00C8 0136 38192818 55"}}
23:59:40 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 010E 00B4 012C 2819090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0082 00DC 0154 015E B091A0 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 00E6 0078 015E 0154 3809292809 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00FA 006E 0136 280908 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 010E 00BE 012C 2819090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00FA 0082 0140 2809090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 0136 2819090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0118 00BE 008C 012C 38190A0819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 00F0 0078 0140 280908 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00AA 012C 281909 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0118 00BE 008C 012C 381909081A 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0122 00B4 014A 2819090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0104 0096 012C 2809090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 03 010E 00BE 0136 2819090819 55"}}
23:59:44 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 010E 00C8 0096 012C 381A0A 55"}}
23:59:45 MQT: tele/sonoff_bridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0118 00C8 008C 0136 381A0A0819 55"}}
![img_20190111_235441](https://user-images.githubusercontent.com/16777381/51063914-6829f480-15fd-11e9-892f-5bb769b307c8.jpg)
![img_20190111_235242](https://user-images.githubusercontent.com/16777381/51063915-6829f480-15fd-11e9-8df6-56eb99d5cb87.jpg)

**Comment by Portisch** [comment]
Try sniffing again with the latest [master](https://github.com/Portisch/RF-Bridge-EFM8BB1/blob/master/Keil%208051%20v9.53%20-%20Release/RF-Bridge-EFM8BB1.hex)!

I close the issue because of a buggy EFM8 firmware - please do a 0xB1 sniffing again and I will reopen the issue.
