### ISSUE TITLE
Possible enhancement

### ISSUE THREAD

**Issue by AlbertWeterings** [Portisch/RF-Bridge-EFM8BB1#8]
There is a issue in ESPURNA where someone is requesting a possibility to make the [buzzer beep](https://github.com/xoseperez/espurna/issues/648). I think this can easily added as a command to the firmware like 0xAA 0xBb 0x55 makes the buzzer beep 1sec.

**Comment by Portisch** [comment]
Done by command 0xC0: fc5774fb956d7b7610b2573d324393bdb2b5b1d2
