### ISSUE TITLE
new protocol Digoo - Nexus

### ISSUE THREAD

**Issue by turin400** [Portisch/RF-Bridge-EFM8BB1#86]
I would like to know if you can add this protocol for humidity and temperature sensors. I would like to buy them and use them with the sonoff bridge. Attachment link with the information.
Greetings and thank you.

[https://forum.pilight.org/showthread.php?tid=3351](url)

[https://github.com/dgomes/homeGW](url)

**Comment by Portisch** [comment]
The rf data looks "normal" and should be possible to receive.
The decoding is not done by this firmware - only the sniffing.

**Comment by turin400** [comment]
I'll buy one and try. Thanks for everything. A greeting.
