### ISSUE TITLE
New 0x03 firmware not receive any data in normal mode.

### ISSUE THREAD

**Issue by spider7611** [Portisch/RF-Bridge-EFM8BB1#90]
### Latest firmware used?
Version 0x03

### Information
Not receiving any data after upgrade to newest firmware. Must downgrade it. What is the problem?

### Sniffed data
No data.

**Comment by Portisch** [comment]
Yes, maybe possible... I have done a "fix" on "normal" mode. I will check it!

**Comment by Portisch** [comment]
Please try this version until I receive my new Arduino:
[RF-Bridge-EFM8BB1.zip fix 0x03, fix standard sniffing](https://github.com/Portisch/RF-Bridge-EFM8BB1/files/2863738/RF-Bridge-EFM8BB1.zip)

**Comment by spider7611** [comment]
Tryed it just now and not working.

**Comment by Portisch** [comment]
Can you please try this version:
[RF-Bridge-EFM8BB1.zip](https://github.com/Portisch/RF-Bridge-EFM8BB1/files/2863798/RF-Bridge-EFM8BB1.zip)

**Comment by spider7611** [comment]
Not working!

**Comment by zerog2k** [comment]
I also notice A6/A7 dont work with digoo door/window switch from a few feet away. (B0 does show raw data sniffing), using 0x03 version (2/11 date). I think earlier 0x03 version from releases page which was Jan 30? date worked, but I think I overwrote this file with newer version :(

**Comment by Portisch** [comment]
I rebased 0x03 and it looks like it break 0xA4. But 0xA6 should work.
Just browse the source for each commit as there is always a hex file included.

This is the first 0x03 version: https://github.com/Portisch/RF-Bridge-EFM8BB1/blob/393d535603095307ee43271f2d02abdb8a4a972d/Keil%208051%20v9.53%20-%20Release/RF-Bridge-EFM8BB1.hex

**Comment by zerog2k** [comment]
Thanks Portisch. You are right, it is A4 decoding which is broken for me. Rolling back to that version it's working.

**Comment by Portisch** [comment]
Solved by https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/a6da9e46497a5e4e9fa9ea3c3207466c3510c75d

New Release:
https://github.com/Portisch/RF-Bridge-EFM8BB1/releases/tag/0x03
