### ISSUE TITLE
Sonoff Door/Window Sensor and PIR Sensor

### ISSUE THREAD

**Issue by MRvH88** [Portisch/RF-Bridge-EFM8BB1#91]
@Portisch Just merged and uploaded the new fixes you committed, however my sonoff door/window and PIR sensor are not being received through default. 

Before the new commits I could receive them in `rfraw 0` (sonoff default/ `0xA4`) or through `rfraw 177`, (`0xB1`), `rfraw 166` (`0xA6`) was not getting any results. But with the new commit I can only get an output though `rfraw 177`, both `rfraw 0` and `rfraw 166` are not giving any results.

If I understand correctly, I should be able to receive standard Sonoff RF devices though all three options ?

Below are some `0xB1` results

`13:07:16 MQT: Sonoff_RF_Bridge/tele/RESULT = {"RfRaw":{"Data":"AA B1 03 04E2 0186 30AC 28181819081819090909090818190908190908190818181909 55"}}
13:07:16 MQT: Sonoff_RF_Bridge/tele/RESULT = {"RfRaw":{"Data":"AA B1 03 0500 0172 30A2 28181819081819090909090818190908190908190818181909 55"}}
13:07:24 MQT: Sonoff_RF_Bridge/tele/RESULT = {"RfRaw":{"Data":"AA B1 03 04F6 017C 30A2 28181819081819090909090818190908190908190818181909 55"}}
13:07:30 MQT: Sonoff_RF_Bridge/tele/RESULT = {"RfRaw":{"Data":"AA B1 03 04EC 0190 30F2 28181819081819090909090818190908190908190818181909 55"}}`

**Comment by Portisch** [comment]
https://github.com/Portisch/RF-Bridge-EFM8BB1/issues/90

**Comment by Portisch** [comment]
Please try this version until I receive my new Arduino:
[RF-Bridge-EFM8BB1.zip fix 0x03, fix standard sniffing](https://github.com/Portisch/RF-Bridge-EFM8BB1/files/2863738/RF-Bridge-EFM8BB1.zip)

**Comment by miit86** [comment]
Same Problem here.
Cannot receive RF data in rfraw 0 or rfraw 166
rf 177 is working great.
Sending rfraw with MQTT functions great.

what i tried:
- flashed tasmota again
- flashed efm again
- sonoff PIR, Sonoff door/windows, KAKU

**Comment by Portisch** [comment]
Solved by https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/a6da9e46497a5e4e9fa9ea3c3207466c3510c75d

New Release:
https://github.com/Portisch/RF-Bridge-EFM8BB1/releases/tag/0x03
