### ISSUE TITLE
B1 to b0 problem 

### ISSUE THREAD

**Issue by plbartek89** [Portisch/RF-Bridge-EFM8BB1#92]
Hello , im tryin to decode my 433mhz door bell 
Can someone help me to decode  & understand that ?
`20:07:07 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00B4 01CC 0082 1360 38192819081818181818181819090909081908181819081818 55"}}
20:07:07 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 008C 01F4 0064 137E 381908190818181818181818190909090819081818190A1A18 55"}}
20:07:07 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0096 01D6 139C 28190819081818181818181819090909081908181819081818 55"}}
20:07:07 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00BE 01C2 0082 1374 38192819081818181818181819090929081908181819081818 55"}}
20:07:29 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00B4 01B8 0078 134C 38192819281818181818181819090909081908181819081818 55"}}
20:07:41 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00BE 01C2 0078 1356 38192819281818181818181819290929081908181819081818 55"}}
20:07:58 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00BE 01C2 0082 1356 38192819281818181818181819092909081908181819081818 55"}}
20:07:58 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 00A0 01D6 137E 28190819081818181818181819090909081908181819081818 55"}}
20:07:58 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00B4 01CC 0082 137E 38190819081818181818181819290909081908181819081818 55"}}55`

**Comment by Portisch** [comment]
### Latest firmware used?
Be sure you tried the [latest release](https://github.com/Portisch/RF-Bridge-EFM8BB1/releases) or the [newest binary](https://github.com/Portisch/RF-Bridge-EFM8BB1/blob/master/Keil%208051%20v9.53%20-%20Release/RF-Bridge-EFM8BB1.hex) of the firmware!

### Information
What device you try to sniff data from? Description? Brand and type?

### Sniffed data
Post your sniffed data by command [0xB1](https://github.com/Portisch/RF-Bridge-EFM8BB1/wiki/0xB1) or [0xA6](https://github.com/Portisch/RF-Bridge-EFM8BB1/wiki/0xA6).

**Comment by plbartek89** [comment]
Hello , i useg latest .hex file 
Its a 433mhz old evology door bell i also have some 433mhz Smoke detectors (smartwares fa22rf)

I use tasmota , with RfRaw AAA655 command no data , with RfRaw AAB155 i recive data , 

`23:58:14 CMD: RfRaw 177
23:58:14 MQT: stat/sonoff/RESULT = {"RfRaw":"ON"}
23:58:14 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AAA055"}}
23:58:18 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 0064 0172 01E0 280918 55"}}

23:58:22 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00D2 01B8 006E 1428 38181818181818181818181819292929281928181819281818 55"}}

23:58:22 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 00BE 01CC 1392 28181818181818181818181819090909081908181819081818 55"}}

23:58:22 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01B8 0078 136A 38181818181818181818181819292929281928181819281818 55"}}

23:58:28 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01AE 006E 1360 38181818181818181818181819292929281928181819281818 55"}}

23:58:28 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00B4 01C2 0082 136A 38181818181818181818181819290909081908181819081818 55"}}

23:58:28 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 00AA 01D6 139C 28181818181818181818181819090909081908181819081818 55"}}

23:58:32 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01AE 006E 1360 38181818181818181818181819292929281928181819281818 55"}}

23:58:34 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00BE 01AE 006E 1356 38181818181818181818181819292929281928181819281818 55"}}

23:58:36 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01B8 0078 1360 38181818181818181818181819292929281928181819281818 55"}}

23:58:36 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00BE 01C2 0082 136A 38181818181818181818181819290909081908181819081818 55"}}
23:58:36 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 00AA 01D6 1392 28181818181818181818181819090909081908181819081818 55"}}

23:58:39 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01B8 0078 1356 38181818181818181818181819292929281928181819281818 55"}}

23:58:44 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01B8 006E 1356 38181818181818181818181819292929281928181819281818 55"}}

23:58:44 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 00B4 01CC 139C 28181818181818181818181819090909081908181819081818 55"}}

23:58:46 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01AE 006E 1360 38181818181818181818181819292929281928181819281818 55"}}

23:58:46 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 03 00B4 01C2 1392 28181818181818181818181819090909081908181819081818 55"}}

23:58:46 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01B8 0078 136A 38181818181818181818181819292929281928181819281818 55"}}

23:58:48 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00C8 01B8 006E 1356 38181818181818181818181819292929281928181819281818 55"}}

23:58:48 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA B1 04 00B4 01C2 0082 1392 38181818181818181818181819290909081908181819081818 55"}}`

**Comment by Portisch** [comment]
Why you just do not use the [BitBucketConverter](https://github.com/Portisch/RF-Bridge-EFM8BB1/wiki/Decode-0xB1-sniffed-data)?
![oscilloscope](https://user-images.githubusercontent.com/3938570/52769737-79698500-3031-11e9-8c1c-9f7fdb32b1c7.jpg)

It has 24bit, decoded value is: 000000000000111101000100b == 0x000F44
