### ISSUE TITLE
Also for Sonoff T1?

### ISSUE THREAD

**Issue by unimatrix27** [Portisch/RF-Bridge-EFM8BB1#93]
Did you consider also to flash an alternative firmware in the Sonoff T1? It also has this RF chip and the "hardwired" functionality is kind of annoying, e.g. it is not possible to disable RF learning after a 4 second button press, which leads to a situation where the device is accidently put into this learning mode.

**Comment by Portisch** [comment]
I do not have the hardware.

**Comment by unimatrix27** [comment]
Ok thank you. I will try to understand the code and maybe come up with something. Maybe it will be enough to just erase the flash of the EFM8BB1
