### ISSUE TITLE
Using advanced protocols with Tasmota

### ISSUE THREAD

**Issue by hcgraf** [Portisch/RF-Bridge-EFM8BB1#94]
Hi,

as you know, I played a bit with the "advanced protocols" feature ;)
But I'm wondering how to best use this with Tasmota...

1. It seems that the advanced learning is not (yet?) supported in Tasmota (RfKey command), right?
  a. What's "advanced learning" (A9) doing, anyway? Seems like more-or-less the same as advanced sniffing with beep...
2. So that means I'd want to enable A6 sniffing by default, right?
  a. Is there any reliable way to do it in Tasmota?
  b. If I need to do it from outside (e.g. MQTT), it might be difficult to ensure that A6 is always enabled, e.g. after a restart...
  c. Will A6 sniffing **stay** enabled? Even after sending something with A8 or even A5?

Any recommendations here?

Thanks,
Hagen

**Comment by Portisch** [comment]
I got told from Tasmota to be compatible with the original firmware. Every additional features are needed to be handled by the "top" firmware (Tasmota).

So wrong place to ask this question.
