### ISSUE TITLE
firmware version 0x04 reports 0x03 version

### ISSUE THREAD

**Issue by zerog2k** [Portisch/RF-Bridge-EFM8BB1#99]
02:44:14 CMD: rfraw 1
02:44:14 MQT: stat/sonoff/RESULT = {"RfRaw":"ON"}
02:44:17 CMD: rfraw 255
02:44:17 MQT: stat/sonoff/RESULT = {"RfRaw":"ON"}
02:44:17 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AA0355"}}
02:44:17 MQT: tele/sonoff/RESULT = {"RfRaw":{"Data":"AAA055"}}

used firmware from latest:
https://github.com/Portisch/RF-Bridge-EFM8BB1/releases/tag/0x04

I think this needs to be bumped?
https://github.com/Portisch/RF-Bridge-EFM8BB1/blob/0x04/inc/Globals.h#L25
`#define FIRMWARE_VERSION	0x03`

**Comment by Portisch** [comment]
Yes, your right. That's because of this: https://github.com/Portisch/RF-Bridge-EFM8BB1/commit/f2cf5845fa7dc11fe37147b24a0399e6c20c4208
I thought when this get merged to the master it will become v4. So the tag is not correct.
